"""add M1 schema constraints and flight number

Revision ID: 9aefb781d521
Revises: fb1088480e8f
Create Date: 2026-08-25 10:00:27.223191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aefb781d521'
down_revision: Union[str, Sequence[str], None] = 'fb1088480e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fare_observations', sa.Column('flight_number', sa.String(length=20), nullable=True))
    op.create_unique_constraint('routes_origin_destination_unique', 'routes', ['origin_airport_id', 'destination_airport_id'])
    op.create_check_constraint('routes_origin_destination_different', 'routes', 'origin_airport_id <> destination_airport_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('routes_origin_destination_different', 'routes', type_='check')
    op.drop_constraint('routes_origin_destination_unique', 'routes', type_='unique')
    op.drop_column('fare_observations', 'flight_number')
    # ### end Alembic commands ###
